In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import re
from bs4 import BeautifulSoup
#from selenium import webdriver

In [2]:
page=requests.get("https://www.cars24.com/buy-used-car?sort=P&storeCityId=3686&pinId=500001&page=2")
content = page.content
soup=BeautifulSoup(content,"html.parser")

In [3]:
desc=soup.find_all("h2",class_="_3FpCg")

In [4]:
description=[]
for i in soup.find_all("h2",class_="_3FpCg"):
    description.append(i.text)

In [5]:
description

['2012 Maruti Swift',
 '2017 Skoda Octavia',
 '2016 Maruti Vitara Brezza',
 '2010 Honda City',
 '2007 Hyundai Santro Xing',
 '2020 Hyundai VENUE',
 '2020 Maruti Ciaz',
 '2011 Maruti Swift',
 '2014 Hyundai Grand i10',
 '2017 Maruti Swift',
 '2017 Honda Jazz',
 '2020 Ford Ecosport',
 '2017 Renault Kwid',
 '2015 Maruti Alto K10',
 '2012 Maruti Wagon R 1.0',
 '2012 Maruti Wagon R 1.0',
 '2015 Hyundai Grand i10',
 '2018 Maruti Vitara Brezza',
 '2019 Maruti Alto',
 '2016 Maruti Wagon R 1.0']

In [6]:
car_type=soup.find_all("p",class_="cvakB")

In [7]:
car_type=[]
for i in soup.find_all("p",class_="cvakB"):
    car_type.append(i.text)

In [8]:
car_type

['ZDI Manual',
 'Style 1.4 TSI MT Manual',
 'VDI Manual',
 'V AT Automatic',
 'GLS Manual',
 '1.5 SX CRDI MT Manual',
 'ALPHA 1.5 AT VTVT SHVS ',
 'VDI Manual',
 'ASTA 1.2 AT VTVT Automatic',
 'VXI OPT Manual',
 'VX  1.2 Manual',
 '1.5 TITANIUM PLUS TI VCT AT Automatic',
 'CLIMBER 1.0 AT Automatic',
 'VXI Manual',
 'VXI Manual',
 'VXI Manual',
 'ASTA AT 1.2 KAPPA VTVT Automatic',
 'VDI AMT Automatic',
 'VXI Manual',
 'VXI Manual']

In [9]:
emi=soup.find_all("div",class_="_2HFRN")

In [10]:
emi=[]
for i in soup.find_all("div",class_="_2HFRN"):
    emi.append(i.text)

In [11]:
emi

['₹10,604/month',
 '₹28,760/month',
 '₹15,104/month',
 '₹10,003/month',
 '₹4,738/month',
 '₹23,196/month',
 '₹24,097/month',
 '₹7,705/month',
 '₹11,038/month',
 '₹12,766/month',
 '₹13,044/month',
 '₹28,044/month',
 '₹9,147/month',
 '₹6,079/month',
 '₹8,170/month',
 '₹7,948/month',
 '₹10,264/month',
 '₹17,807/month',
 '₹9,056/month',
 '₹8,855/month']

In [12]:
original_price=soup.find_all("div",class_="_7udZZ")

In [13]:
original_price=[]
for i in soup.find_all("div",class_="_7udZZ"):
    original_price.append(i.text)

In [14]:
original_price

['₹4,76,699',
 '₹12,92,899',
 '₹6,78,999',
 '₹4,49,699',
 '₹2,12,999',
 '₹10,42,799',
 '₹10,83,299',
 '₹3,46,399',
 '₹4,96,199',
 '₹5,73,899',
 '₹5,86,399',
 '₹12,60,699',
 '₹4,11,199',
 '₹2,73,299',
 '₹3,67,299',
 '₹3,57,299',
 '₹4,61,399',
 '₹8,00,499',
 '₹4,07,099',
 '₹3,98,099']

In [15]:
specifications=soup.find_all("ul",class_="bVR0c")

In [16]:
specification=[]
for i in soup.find_all("ul",class_="bVR0c"):
    specification.append(i.text)

In [17]:
specification

['78,819 km2nd OwnerDiesel',
 '47,264 km1st OwnerPetrol',
 '1,53,631 km1st OwnerDiesel',
 '1,52,381 km1st OwnerPetrol',
 '38,634 km1st OwnerPetrol',
 '40,139 km1st OwnerDiesel',
 '35,019 km1st OwnerPetrol',
 '1,11,043 km1st OwnerDiesel',
 '22,815 km1st OwnerPetrol',
 '1,04,760 km1st OwnerPetrol',
 '75,366 km2nd OwnerPetrol',
 '5,634 km1st OwnerPetrol',
 '36,933 km2nd OwnerPetrol',
 '2,34,695 km1st OwnerPetrol',
 '78,088 km1st OwnerPetrol',
 '73,245 km1st OwnerPetrol',
 '78,484 km1st OwnerPetrol',
 '81,477 km2nd OwnerDiesel',
 '41,432 km1st OwnerPetrol',
 '39,789 km1st OwnerPetrol']

In [21]:
citycode = [2,134,5,3686,4709,2738,5732,777,2423,2987,769,6,290,8184,1605]
cities = ['New Delhi','Noida','Gurgon','Hyderabad','Banglore','Mumbai','Chennai','Kolkata','Pune','Bhopal','Chandigarh','Faridabad','Lucknow','patna','Surat']
brands = ['TOYOTA','MARUTI','VOLKSWAGEN','HONDA','HYUNDAI','KIA','FORD','MAHINDRA','RENAULT','SKODA','BMW','VOLVO','BAJAJ']

for b in brands:
    for c in citycode:
        url = 'https://www.cars24.com/buy-used-car?sort=P&search={}&storeCityId=8597={}'.format(b,c)
        print(url)

https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=TOYOTA&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=MARUTI&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=VOLKSWAGEN&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=HONDA&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=HYUNDAI&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=KIA&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=FORD&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=MAHINDRA&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=RENAULT&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=SKODA&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=BMW&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=VOLVO&storeCityId=8597=1605
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=2
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=134
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=5
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=3686
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=4709
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=2738
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=5732
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=777
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=2423
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=2987
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=769
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=6
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=290
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=8184
https://www.cars24.com/buy-used-car?sort=P&search=BAJAJ&storeCityId=8597=1605

In [53]:
res = dict(zip(citycode, cities))

In [54]:
df1['Updated_City'] = df1['City'].map(res)

In [23]:
citycode = [2,134,5,3686,4709,2738,5732,777,2423,2987,769,6,290,8184,1605]
cities = ['New Delhi','Noida','Gurgon','Hyderabad','Banglore','Mumbai','Chennai','Kolkata','Pune','Bhopal','Chandigarh','Faridabad','Lucknow','patna','Surat']
brands = ['TOYOTA','MARUTI','VOLKSWAGEN','HONDA','HYUNDAI','KIA','FORD','MAHINDRA','RENAULT','SKODA','BMW','VOLVO','BAJAJ']
description=[]
car_type=[]
emi=[]
original_price=[]
specification=[]
city = []
for b in brands:
    for c in citycode:
        url = 'https://www.cars24.com/buy-used-car?sort=P&search={}&storeCityId={}'.format(b,c)
        
        page = requests.get(url)
        soup = BeautifulSoup(page.content)        
    # DEscription
        for i in soup.find_all("h2",class_="_3FpCg"):
            description.append(i.text)
            city.append(c)
        #Car_type
        for i in soup.find_all("p",class_="cvakB"):
            car_type.append(i.text)   
        #EMI\
        for i in soup.find_all("div",class_="_2HFRN"):
            emi.append(i.text)
        #original_price
        for i in soup.find_all("div",class_="_7udZZ"):
            original_price.append(i.text)
        #specification
        for i in soup.find_all("ul",class_="bVR0c"):
            specification.append(i.text)

In [24]:
print(len(description))
print(len(car_type))
print(len(specification))
print(len(car_type))
print(len(original_price))
print(len(emi))

1287
1287
1287
1287
1287
1287

In [51]:
df1 = pd.DataFrame({'Description': description,
                    'Car_Type'  :  car_type,
                    'EMI':   emi,
                    'Original_price':original_price,
                    'Specification':specification,
                    'City' :    city})

In [55]:
df1

,Description,Car_Type,EMI,Original_price,Specification,City,Updated_City
0,2014 Toyota Innova,2.5 VX 8 STR BS IV Manual,"₹22,970/month","₹10,32,599","69,958 km1st OwnerDiesel",2,New Delhi
1,2013 Toyota Innova,2.5 GX 7 STR BS IV Manual,"₹14,236/month","₹6,39,999","1,58,103 km1st OwnerDiesel",2,New Delhi
2,2021 Toyota YARIS,G MT Manual,"₹21,622/month","₹9,71,999","11,863 km1st OwnerPetrol",2,New Delhi
3,2013 Toyota Fortuner,3.0 AT 4X2 Automatic,"₹27,432/month","₹12,33,199","1,97,792 km1st OwnerDiesel",2,New Delhi
4,2013 Toyota Innova,2.5 GX 8 STR BS IV Manual,"₹15,798/month","₹7,10,199","63,747 km1st OwnerDiesel",2,New Delhi
...,...,...,...,...,...,...,...
1282,2014 BMW 3 Series,320D LUXURYLINE Automatic,"₹32,922/month","₹14,79,999","75,353 km3rd OwnerDiesel",2423,Pune
1283,2013 BMW 3 Series,320D LUXURYLINE Automatic,"₹30,584/month","₹13,74,899","1,53,096 km3rd OwnerDiesel",769,Chandigarh
1284,2013 BMW 5 Series,520D LUXURY LINE Automatic,"₹41,777/month","₹18,78,099","46,477 km1st OwnerDiesel",6,Faridabad
1285,2012 BMW 3 Series,320D Automatic,"₹20,576/month","₹9,25,000","71,923 km2nd OwnerDiesel",6,Faridabad
1286,2012 Volvo S60,SUMMUM D5 Automatic,"₹16,884/month","₹7,58,999","41,361 km2nd OwnerDiesel",2,New Delhi

### Upload Data into CSV file

In [59]:
df1.to_csv("Used-Car-Details1.csv",index=False)

### Impot CSV file

In [60]:
df1=pd.read_csv("Used-Car-Details1.csv")

In [61]:
df1

,Description,Car_Type,EMI,Original_price,Specification,City,Updated_City
0,2014 Toyota Innova,2.5 VX 8 STR BS IV Manual,"₹22,970/month","₹10,32,599","69,958 km1st OwnerDiesel",2,New Delhi
1,2013 Toyota Innova,2.5 GX 7 STR BS IV Manual,"₹14,236/month","₹6,39,999","1,58,103 km1st OwnerDiesel",2,New Delhi
2,2021 Toyota YARIS,G MT Manual,"₹21,622/month","₹9,71,999","11,863 km1st OwnerPetrol",2,New Delhi
3,2013 Toyota Fortuner,3.0 AT 4X2 Automatic,"₹27,432/month","₹12,33,199","1,97,792 km1st OwnerDiesel",2,New Delhi
4,2013 Toyota Innova,2.5 GX 8 STR BS IV Manual,"₹15,798/month","₹7,10,199","63,747 km1st OwnerDiesel",2,New Delhi
...,...,...,...,...,...,...,...
1282,2014 BMW 3 Series,320D LUXURYLINE Automatic,"₹32,922/month","₹14,79,999","75,353 km3rd OwnerDiesel",2423,Pune
1283,2013 BMW 3 Series,320D LUXURYLINE Automatic,"₹30,584/month","₹13,74,899","1,53,096 km3rd OwnerDiesel",769,Chandigarh
1284,2013 BMW 5 Series,520D LUXURY LINE Automatic,"₹41,777/month","₹18,78,099","46,477 km1st OwnerDiesel",6,Faridabad
1285,2012 BMW 3 Series,320D Automatic,"₹20,576/month","₹9,25,000","71,923 km2nd OwnerDiesel",6,Faridabad
1286,2012 Volvo S60,SUMMUM D5 Automatic,"₹16,884/month","₹7,58,999","41,361 km2nd OwnerDiesel",2,New Delhi